# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 13:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('image', models.FileField(upload_to=b'images/')),
                ('initial_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category', models.CharField(
                    choices=[(b'all', b'All'), (b'art', b'Art'), (b'jewelry', b'Jewelry'), (b'antiques', b'Antiques'),
                             (b'furniture', b'Furniture'), (b'collectibles', b'Collectibles'),
                             (b'home&garden', b'Home & Garden'), (b'fashion', b'Fashion')], default=b'all',
                    max_length=100)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('creator', models.CharField(max_length=191, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
